# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-04 22:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 4, 22, 12, 3, 662191, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
